In [1]:
import numpy as np
from LinSolve import LinSolve
from Vetor import Vetor, Dot
from Matriz import Matriz
from Fatoracao import Fat

In [2]:
n = 3

H = np.fromfunction(lambda i, j: 1/(i+j+1), (n,n), dtype=int)
I = np.identity(n)
#Inicialização do objeto Fat(), a partir dele podemos calcular as três fatorações da matriz de Hilbert.
A = Fat(H)

#Cálculo das fatorações a partir do objeto A e inicialização dos objetos Matriz com as fatorações obtidas.
R = Matriz(A.cholesky()) #Cholesky
q1, r1 = A.GS() #QR com Gram-Schmidt
Q1 = Matriz(q1)
R1 = Matriz(r1)
q2, r2 = A.rot() #QR rotação
Q2 = Matriz(q2)
R2 = Matriz(r2)

print(Q1.matriz)
print(R1.matriz)
print("\n")
print(Q2.matriz)
print(R2.matriz)
print("\n")

print(np.dot(R.matriz.transpose(), R.matriz))
print(np.dot(Q1.matriz, R1.matriz))
print(np.dot(Q2.matriz, R2.matriz))

[[ 0.85714286  0.76822128 -0.49692935]
 [ 0.42857143  0.51214752  0.54210474]
 [ 0.28571429  0.38411064  0.67763093]]
[[1.16666667 0.         0.45      ]
 [0.         0.65085414 0.        ]
 [0.         0.         0.10540926]]


[[ 0.85714286 -0.50160492  0.11704115]
 [ 0.42857143  0.56848557 -0.70224688]
 [ 0.28571429  0.65208639  0.70224688]]
[[ 1.16666667e+00  6.42857143e-01  4.50000000e-01]
 [ 0.00000000e+00  1.01714330e-01  1.05337032e-01]
 [ 0.00000000e+00 -6.93889390e-18  3.90137157e-03]]


[[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]
[[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]
[[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]


In [6]:
#Resolução do sistema HX=I com cholesky.
Y = np.zeros((1, n))
for i in range(n):
    y = LinSolve(R.matriz.transpose(), I[:, i]).Solve()
    Y = np.vstack((Y, y))
Y = np.delete(Y, 0, 0)

X = np.zeros((1, n))
for i in range(n):
    x = LinSolve(R.matriz, Y[i, :]).Solve()
    X = np.vstack((X, x))
X = np.delete(X, 0, 0)
If = np.dot(H, X)
print(X)
print(If)

[[   9.  -36.   30.]
 [ -36.  192. -180.]
 [  30. -180.  180.]]
[[ 1.00000000e+00 -7.10542736e-15  7.10542736e-15]
 [ 8.88178420e-16  1.00000000e+00  7.10542736e-15]
 [ 8.88178420e-16  0.00000000e+00  1.00000000e+00]]


In [7]:
#Resolução do sistema HX=I com Gram-Schmidt.
X = np.zeros((1,n))
for i in range(n):
    x = LinSolve(R1.matriz, Q1.transpose[:, i]).Solve()
    X = np.vstack((X,x))
X = np.delete(X, 0, 0)
If = np.dot(H, X)

print(X)
print(If)

[[ 2.55306122  1.18032787 -4.71428571]
 [-1.61632653  0.78688525  5.14285714]
 [-2.23469388  0.59016393  6.42857143]]
[[ 1.00000000e+00  1.77049180e+00  3.55271368e-15]
 [ 1.79081633e-01  1.00000000e+00  9.64285714e-01]
 [-6.66133815e-16  7.08196721e-01  1.00000000e+00]]


In [8]:
#Resolução do sistema HX=I com rotações.
X = np.zeros((1,n))
for i in range(n):
    x = LinSolve(R2.matriz, Q2.transpose[:, i]).Solve()
    X = np.vstack((X,x))
X = np.delete(X, 0, 0)
If = np.dot(H, X)

print(X)
print(If)

[[   9.  -36.   30.]
 [ -36.  192. -180.]
 [  30. -180.  180.]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-4.44089210e-15  1.00000000e+00 -1.42108547e-14]
 [-8.88178420e-16  0.00000000e+00  1.00000000e+00]]


In [ ]:
x1 = np.linalg.solve(R1.matriz, Q1.transpose[:, 0])
x2 = np.linalg.solve(R1.matriz, Q1.transpose[:, 1])
x3 = np.linalg.solve(R1.matriz, Q1.transpose[:, 2])

X = np.array([x1, x2, x3]).transpose()
If = np.dot(H, X)

print(X)
print(If)